Repository nextcloud/fulltextsearch, pull requests merged in 2024-08, with the labels that each got.

#834 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#855 fix: Add navigation entry by closure
  lib/AppInfo/Application.php
Labels: bug, 3. to review

#854 chore: Adjust version for Nextcloud 30
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#835 Updating appstore-build-publish.yml workflow from template
  .github/workflows/appstore-build-publish.yml
Labels: dependencies
